// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FilePathFetcher is an autogenerated mock type for the FilePathFetcher type
type FilePathFetcher struct {
	mock.Mock
}

// GetFilePath provides a mock function with given fields:
func (_m *FilePathFetcher) GetFilePath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type NewFilePathFetcherT interface {
	mock.TestingT
	Cleanup(func())
}

// NewFilePathFetcher creates a new instance of FilePathFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFilePathFetcher(t NewFilePathFetcherT) *FilePathFetcher {
	mock := &FilePathFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
