// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Display is an autogenerated mock type for the Display type
type Display struct {
	mock.Mock
}

// Output provides a mock function with given fields: val
func (_m *Display) Output(val string) {
	_m.Called(val)
}

type NewDisplayT interface {
	mock.TestingT
	Cleanup(func())
}

// NewDisplay creates a new instance of Display. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDisplay(t NewDisplayT) *Display {
	mock := &Display{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
